# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget System Main Window OpenGL Network Graphics Freetype OpenAL VORBIS FLAC Audio)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target System
add_library(System SHARED IMPORTED)

set_target_properties(System PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
)

# Create imported target Main
add_library(Main STATIC IMPORTED)

set_target_properties(Main PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
)

# Create imported target Window
add_library(Window SHARED IMPORTED)

set_target_properties(Window PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
  INTERFACE_LINK_LIBRARIES "System"
)

# Create imported target OpenGL
add_library(OpenGL INTERFACE IMPORTED)

set_target_properties(OpenGL PROPERTIES
  INTERFACE_LINK_LIBRARIES "opengl32"
)

# Create imported target Network
add_library(Network SHARED IMPORTED)

set_target_properties(Network PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
  INTERFACE_LINK_LIBRARIES "System"
)

# Create imported target Graphics
add_library(Graphics SHARED IMPORTED)

set_target_properties(Graphics PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
  INTERFACE_LINK_LIBRARIES "Window"
)

# Create imported target Freetype
add_library(Freetype INTERFACE IMPORTED)

set_target_properties(Freetype PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/headers/freetype2"
  INTERFACE_LINK_LIBRARIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/freetype.lib"
)

# Create imported target OpenAL
add_library(OpenAL INTERFACE IMPORTED)

set_target_properties(OpenAL PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/headers/AL"
  INTERFACE_LINK_LIBRARIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/openal32.lib"
)

# Create imported target VORBIS
add_library(VORBIS INTERFACE IMPORTED)

set_target_properties(VORBIS PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OV_EXCLUDE_STATIC_CALLBACKS"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/headers;C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/headers"
  INTERFACE_LINK_LIBRARIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/vorbisenc.lib;C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/vorbisfile.lib;C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/vorbis.lib;C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/ogg.lib"
)

# Create imported target FLAC
add_library(FLAC INTERFACE IMPORTED)

set_target_properties(FLAC PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "FLAC__NO_DLL"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/headers"
  INTERFACE_LINK_LIBRARIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/extlibs/libs-msvc-universal/x64/flac.lib"
)

# Create imported target Audio
add_library(Audio SHARED IMPORTED)

set_target_properties(Audio PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/iltwl/Documents/SparkEditor/extlibs/SparkEngine/extlibs/SFML/include"
  INTERFACE_LINK_LIBRARIES "System"
)

# Import target "System" for configuration "Debug"
set_property(TARGET System APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(System PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-system-d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Debug/sfml-system-d-3.dll"
  )

# Import target "Main" for configuration "Debug"
set_property(TARGET Main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-main-d.lib"
  )

# Import target "Window" for configuration "Debug"
set_property(TARGET Window APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Window PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-window-d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Debug/sfml-window-d-3.dll"
  )

# Import target "Network" for configuration "Debug"
set_property(TARGET Network APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Network PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-network-d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Debug/sfml-network-d-3.dll"
  )

# Import target "Graphics" for configuration "Debug"
set_property(TARGET Graphics APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Graphics PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-graphics-d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Debug/sfml-graphics-d-3.dll"
  )

# Import target "Audio" for configuration "Debug"
set_property(TARGET Audio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Audio PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Debug/sfml-audio-d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Debug/sfml-audio-d-3.dll"
  )

# Import target "System" for configuration "Release"
set_property(TARGET System APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(System PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-system.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Release/sfml-system-3.dll"
  )

# Import target "Main" for configuration "Release"
set_property(TARGET Main APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-main.lib"
  )

# Import target "Window" for configuration "Release"
set_property(TARGET Window APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Window PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-window.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Release/sfml-window-3.dll"
  )

# Import target "Network" for configuration "Release"
set_property(TARGET Network APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Network PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-network.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Release/sfml-network-3.dll"
  )

# Import target "Graphics" for configuration "Release"
set_property(TARGET Graphics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Graphics PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-graphics.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Release/sfml-graphics-3.dll"
  )

# Import target "Audio" for configuration "Release"
set_property(TARGET Audio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Audio PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/Release/sfml-audio.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/Release/sfml-audio-3.dll"
  )

# Import target "System" for configuration "MinSizeRel"
set_property(TARGET System APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(System PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-system.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/MinSizeRel/sfml-system-3.dll"
  )

# Import target "Main" for configuration "MinSizeRel"
set_property(TARGET Main APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-main.lib"
  )

# Import target "Window" for configuration "MinSizeRel"
set_property(TARGET Window APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Window PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-window.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/MinSizeRel/sfml-window-3.dll"
  )

# Import target "Network" for configuration "MinSizeRel"
set_property(TARGET Network APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Network PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-network.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/MinSizeRel/sfml-network-3.dll"
  )

# Import target "Graphics" for configuration "MinSizeRel"
set_property(TARGET Graphics APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Graphics PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-graphics.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/MinSizeRel/sfml-graphics-3.dll"
  )

# Import target "Audio" for configuration "MinSizeRel"
set_property(TARGET Audio APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Audio PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/MinSizeRel/sfml-audio.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/MinSizeRel/sfml-audio-3.dll"
  )

# Import target "System" for configuration "RelWithDebInfo"
set_property(TARGET System APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(System PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-system.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/RelWithDebInfo/sfml-system-3.dll"
  )

# Import target "Main" for configuration "RelWithDebInfo"
set_property(TARGET Main APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-main.lib"
  )

# Import target "Window" for configuration "RelWithDebInfo"
set_property(TARGET Window APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Window PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-window.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/RelWithDebInfo/sfml-window-3.dll"
  )

# Import target "Network" for configuration "RelWithDebInfo"
set_property(TARGET Network APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Network PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-network.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/RelWithDebInfo/sfml-network-3.dll"
  )

# Import target "Graphics" for configuration "RelWithDebInfo"
set_property(TARGET Graphics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Graphics PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-graphics.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/RelWithDebInfo/sfml-graphics-3.dll"
  )

# Import target "Audio" for configuration "RelWithDebInfo"
set_property(TARGET Audio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Audio PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/lib/RelWithDebInfo/sfml-audio.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/iltwl/Documents/SparkEditor/bulid/bin/RelWithDebInfo/sfml-audio-3.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
